config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  resources :products do
    resources :user_stories
    resources :sprint_backlogs
  end
  resources :developments, only: [:index] do
    member do
      get 'information'
    end
  end
  resources :tasks

end

app/models/user_story.rb
class UserStory < ActiveRecord::Base
  has_many :acceptances, dependent: :destroy
  has_many :tasks, dependent: :destroy
  belongs_to :product
  accepts_nested_attributes_for :acceptances, reject_if: lambda {|attributes| attributes['criterion'].blank?}
  belongs_to :sprint_backlog
  before_save {self.title = title.upcase}


  def self.update_sprint_backlog_id(params, sprint_backlog_id)
    UserStory.where('sprint_backlog_id = ? OR sprint_backlog_id IS ?', sprint_backlog_id, nil).each do |user_story|
      if params.has_key?(user_story.id.to_s)
        user_story.update_attribute(:sprint_backlog_id, sprint_backlog_id)
      else
        user_story.update_attribute(:sprint_backlog_id, '')
      end
    end
  end

  def self.create_sprint_backlog_id(params, sprint_backlog_id)
      UserStory.all.each do |user_story|
      if params.has_key?(user_story.id.to_s)
        user_story.update_attribute(:sprint_backlog_id, sprint_backlog_id)
      end
    end
  end
end



    

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController

  def index
    # render :text => params
    @product = Product.find(params[:product_id])
    @user_stories = @product.user_stories
  end
  def show
    @product = Product.find(params[:product_id])
    @user_story = UserStory.find(params[:id])
  end
  def new
    # render :text => params
    @product = Product.find(params[:product_id])
    @user_story = UserStory.new
    5.times {@user_story.acceptances.new}
  end

  def edit
    # render :text => params
    @product = Product.find(params[:product_id])
    @user_story = UserStory.find(params[:id])
    (5 - @user_story.acceptances.count).times {@user_story.acceptances.new}
  end

  def create
    # render :text => params
    product = Product.find(params[:product_id])
    user_story  = UserStory.new(user_story_params)
    user_story.product_id = product.id
    if user_story.save
      flash[:success] = 'Historia de usuario ingresada con exito'
      redirect_to product_user_stories_path
    end
  end

  def update
    # render :text => params
    user_story = UserStory.find(params[:id])
    if user_story.update(user_story_params)
      flash[:success] = 'Historia de usuario actualizada con exito'
      redirect_to product_user_story_path(params[:product_id], params[:id])
    end
  end

  def destroy
    # render :text => params
    user_story = UserStory.find(params[:id])
    if user_story.destroy
      flash[:success] = 'Historia de usuario eliminada con exito'
      redirect_to product_user_stories_path
    end
  end
  private
  def user_story_params
    params.require(:user_story).permit(:title, :content, acceptances_attributes: [:id, :criterion])
  end
end

app/helpers/user_stories_helper.rb
module UserStoriesHelper
end

app/views/user_stories/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Productos', products_path %></li>
    <li class="active">Product Backlog</li>
  </ol>
  <%= form_for [@product,@user_story] do |f| %>
      <div class="row">
        <div class="col-md-4">
          <p>HISTORIA</p>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control', rows: '8' %>
          </div>
        </div>
        <div class="col-md-4">
          <p>CRITERIOS DE ACEPTACIÓN</p>
          <%= f.fields_for :acceptances do |acceptance_form| %>
              <div class="form-group">
                <%= acceptance_form.label :criterion %>
                <%= acceptance_form.text_area :criterion, class: 'form-control' %>
              </div>
          <% end %>
        </div>
        <div class="col-md-4"></div>
      </div>
      <%= f.submit 'Actualizar' %>
  <% end %>
  <%= link_to 'Mostrar', product_user_story_path(@product.id, @user_story.id) %> |
  <%= link_to 'Lista de historias', product_user_stories_path %>
</div>

app/views/user_stories/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Productos', products_path %></li>
    <li class="active">Product Backlog</li>
  </ol>
  <h1>PRODUCT BACKLOG</h1>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>HISTORIAS DE USUARIO</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @user_stories.each do |user_story| %>
        <tr>
          <td><%= user_story.title %></td>
          <td><%= link_to 'Mostrar', product_user_story_path(@product.id, user_story.id) %></td>
          <td><%= link_to 'Editar', edit_product_user_story_path(@product.id, user_story.id) %></td>
          <td><%= link_to 'Eliminar',  product_user_story_path(@product.id, user_story.id), method: :delete, data: {confirm: 'Esta seguro?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to 'Nueva historia', new_product_user_story_path %> |
  <%= link_to 'Sprints', product_sprint_backlogs_path(@product.id) %>
</div>

app/views/user_stories/new.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Productos', products_path %></li>
    <li class="active">Product Backlog</li>
  </ol>
  <%= form_for [@product, @user_story] do |f| %>
     <div class="row">
       <div class="col-md-4">
         <p>HISTORIAS</p>
         <div class="form-group">
           <%= f.label :title %>
           <%= f.text_field :title, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.label :content %>
           <%= f.text_area :content, class: 'form-control', rows: '8' %>
         </div>
       </div>
       <div class="col-md-4">
         <p>CRITERIOS DE ACEPTACIÓN</p>
         <%= f.fields_for :acceptances do |acceptance_form| %>
           <div class="form-group">
             <%= acceptance_form.label :criterion %>
             <%= acceptance_form.text_area :criterion, class: 'form-control' %>
           </div>
         <% end %>
       </div>
       <div class="col-md-4"></div>
     </div>
     <%= f.submit 'Guardar' %>
  <% end %>
  <%= link_to 'Lista de historias', product_user_stories_path %>
</div>

app/views/user_stories/show.html.erb
<style>
  .user-story{
    text-align: justify;
  }
  .user-story-title{
    text-align: center;
  }
  mark{
    color: green;
  }
</style>
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Productos', products_path %></li>
    <li class="active">Product Backlog</li>
  </ol>
  <div class="row">
    <div class="col-md-3">
      <p class="user-story-title"><%= @user_story.title %></p>
      <%= highlight(simple_format(@user_story.content, class: 'user-story'),/Como|Quiero|Para/) %>
    </div>
    <div class="col-md-6">
      <p>CRITERIOS DE ACEPTACIÓN</p>
      <% @user_story.acceptances.each_with_index do |acceptance, index| %>
        <p><%= index + 1 %>.-<%= acceptance.criterion %></p>
      <% end %>
    </div>
  </div>

  <%= link_to 'Editar', edit_product_user_story_path(@product.id,@user_story.id) %> |
  <%= link_to 'Lista de historias',  product_user_stories_path(@product.id) %>
</div>