config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  resources :products do
    resources :user_stories
    resources :sprint_backlogs
  end
  resources :developments, only: [:index] do
    member do
      get 'information'
    end
  end
  resources :tasks

end

app/models/sprint_backlog.rb
class SprintBacklog < ActiveRecord::Base
  has_many :user_stories, dependent: :nullify
  belongs_to :product
  before_save {self.title = title.upcase}
end

app/controllers/sprint_backlogs_controller.rb
class SprintBacklogsController < ApplicationController
  def index
    @product = Product.find(params[:product_id])
    @sprints = @product.sprint_backlogs
    # render text: params
  end
  def show
    @product = Product.find(params[:product_id])
    @sprint_backlog = SprintBacklog.find(params[:id])
  end
  def new
    # render :text => params
    @product = Product.find(params[:product_id])
    @sprint_backlog = SprintBacklog.new
    @user_stories = @product.user_stories.where('sprint_backlog_id IS ?', nil)
    # @user_stories = UserStory.where('sprint_backlog_id IS ?', nil)
  end

  def edit
    @product = Product.find(params[:product_id])
    @sprint_backlog = SprintBacklog.find(params[:id])
    @user_stories =@product.user_stories.where('sprint_backlog_id = ? OR sprint_backlog_id IS ?', @sprint_backlog.id, nil)
    # @user_stories = UserStory.where('sprint_backlog_id = ? OR sprint_backlog_id IS ?', @sprint_backlog.id, nil)
  end
  def create
    # render :text => params
    product = Product.find(params[:product_id])
    sprint_backlog = SprintBacklog.new(sprint_backlog_params)
    sprint_backlog.product = product
    sprint_backlog.save
    create_sprint_backlog_id(sprint_backlog.id)
    redirect_to product_sprint_backlog_path(product, sprint_backlog)
  end

  def update
    # render :text => params
    product = Product.find(params[:product_id])
    sprint_backlog = SprintBacklog.find(params[:id])
    sprint_backlog.update(sprint_backlog_params)
    update_sprint_backlog_id(sprint_backlog.id)
    redirect_to product_sprint_backlog_path(product.id, sprint_backlog.id)
  end

  def destroy
    # render :text => params
    product = Product.find(params[:product_id])
    sprint = SprintBacklog.find(params[:id])
    sprint.destroy
    redirect_to product_sprint_backlogs_path(product.id)
  end
  private
  def sprint_backlog_params
    params.require(:sprint_backlog).permit(:title, :description)
  end

  def update_sprint_backlog_id(sprint_backlog_id)
    UserStory.update_sprint_backlog_id(params, sprint_backlog_id)
  end

  def create_sprint_backlog_id(sprint_backlog_id)
    UserStory.create_sprint_backlog_id(params, sprint_backlog_id)
  end
end

app/helpers/sprint_backlogs_helper.rb
module SprintBacklogsHelper
end

app/views/sprint_backlogs/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Productos', products_path %></li>
    <li><%= link_to 'Product Backlog', product_user_stories_path(@product) %></li>
    <li class="active">Sprints</li>
  </ol>
  <%= form_for [@product,@sprint_backlog] do |f| %>
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description  %>
            <%= f.text_area :description, class: 'form-control', rows: '8' %>
          </div>
        </div>
        <div class="col-md-4">
          <% @user_stories.each do |user_story| %>
              <div class="checkbox">
                <% if user_story.sprint_backlog_id == @sprint_backlog.id %>
                  <%= check_box_tag(user_story.id, '1',true) %>
                  <%= label_tag(user_story.title) %>
                <% else %>
                    <%= check_box_tag(user_story.id) %>
                    <%= label_tag(user_story.title) %>
                <% end %>
              </div>
          <% end %>
        </div>
      </div>

      <%= f.submit %>
  <% end %>
  <%= link_to 'Mostrar', product_sprint_backlog_path(@product,@sprint_backlog) %> |
  <%= link_to 'Lista de sprints', product_sprint_backlogs_path(@product) 	 %>
</div>

app/views/sprint_backlogs/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Productos', products_path %></li>
    <li><%= link_to 'Product Backlog', product_user_stories_path(@product) %></li>
    <li class="active">Sprints</li>
  </ol>
  <h1>SPRINTS</h1>

  <table class="table table-hover">
    <thead>
    <tr>
      <th>SPRINT BACKLOG</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @sprints.each do |sprint| %>
        <tr>
          <td><%= sprint.title %></td>
          <td><%= link_to 'Mostrar', product_sprint_backlog_path(@product, sprint) %></td>
          <td><%= link_to 'Editar', edit_product_sprint_backlog_path(@product, sprint) %></td>
          <td><%= link_to 'Eliminar', product_sprint_backlog_path(@product, sprint), method: :delete, data: {confirm: 'Esta seguro'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to 'Nuevo Sprint', new_product_sprint_backlog_path(@product.id) %> |
  <%= link_to 'Desarrollo', information_development_path(@product.user_stories.last) %>
</div>

app/views/sprint_backlogs/new.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Productos', products_path %></li>
    <li><%= link_to 'Product Backlog', product_user_stories_path(@product) %></li>
    <li class="active">Sprints</li>
  </ol>
  <%= form_for [@product,@sprint_backlog] do |f| %>
    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description  %>
          <%= f.text_area :description, class: 'form-control', rows: '8' %>
        </div>
      </div>
      <div class="col-md-4">
        <% @user_stories.each do |user_story| %>
          <div class="checkbox">
            <%= check_box_tag(user_story.id) %>
            <%= label_tag(user_story.title) %>
          </div>
        <% end %>
      </div>
    </div>

    <%= f.submit %>
  <% end %>
  <%= link_to 'Lista de sprints',  product_sprint_backlogs_path(@product.id) %>
</div>

app/views/sprint_backlogs/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to 'Productos', products_path %></li>
    <li><%= link_to 'Product Backlog', product_user_stories_path(@product) %></li>
    <li class="active">Sprints</li>
  </ol>
  <div class="row">
    <div class="col-md-3">
      <p><%= @sprint_backlog.title %></p>
      <p><%= @sprint_backlog.description %></p>
    </div>
    <div class="col-md-3">
      <p>SPRINT BACKLOG</p>
      <% @sprint_backlog.user_stories.each_with_index  do |user_story, index| %>
          <p><%= index + 1 %>.-<%= user_story.title %></p>
      <% end %>
    </div>
  </div>
  <%= link_to 'Editar', edit_product_sprint_backlog_path(@product.id, @sprint_backlog.id) %> |
  <%= link_to 'Lista de Sprints', product_sprint_backlogs_path(@product.id) %>
</div>