config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  resources :products do
    resources :user_stories
    resources :sprint_backlogs
  end
  resources :developments, only: [:index] do
    member do
      get 'information'
    end
  end
  resources :tasks

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :user_stories, dependent: :destroy
  has_many :sprint_backlogs, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class:'form-control'  %>
  </div>
  <div class="actions">
    <%= f.submit 'Crear producto', class:'btn btn-success' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li class="active">Productos</li>
  </ol>
  <h1>Editing Product</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>

</div>

app/views/products/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li class="active">Productos</li>
  </ol>
  <p id="notice"><%= notice %></p>

  <h1>LISTA DE PROYECTOS</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
      <th>Product backlog</th>
    </tr>
    </thead>

    <tbody>
    <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= link_to 'Mostrar', product %></td>
          <td><%= link_to 'Editar', edit_product_path(product) %></td>
          <td><%= link_to 'eliminar', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Product Backlog', product_user_stories_path(product) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo producto', new_product_path %>

</div>

app/views/products/new.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li class="active">Productos</li>
  </ol>
  <h1>Producto nuevo</h1>

  <%= render 'form' %>

  <%= link_to 'Back', products_path %>

</div>

app/views/products/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li class="active">Productos</li>
  </ol>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>

  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>

</div>